version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: MultiShop.Discount
    restart: always
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyStr0ngP@ssw0rd2025!
      - MSSQL_TLS_DISABLED=1 

 
    volumes:
      - sql_data:/var/opt/mssql 

volumes:
  sql_data:
    driver: local
