version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: MultiShop.Message
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=MyStr0ngP@ssw0rd2025!
      - POSTGRES_DB=MultiShopMessageDb
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local
